### ISSUE TITLE
PRACTICA 7 HILOS EN WINDOWS FORMS KEVIN CRZ, ARCANGEL GNZ CRZ, JUAN ANT. NIC. PRZ.

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-4as_coders#1]
[PRACTICA 7 HILOS EN WINDOWS FORMS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-4as_coders/files/15133710/PRACTICA.7.HILOS.EN.WINDOWS.FORMS.pdf)

**Comment by RodolfoNV** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
